### PR TITLE
Log election searches

### PR DESCRIPTION
**Pull request by mrichards42**
We seem to be running out of memory on some pods. My suspicion is that it _could_ be related to caching elections/authority searches, since the search keys are often unique per user. I'd like to get some data on that by logging election searches.

### CODE REVIEW

**Comment by li-at-dw** [comment]
This is super interesting to me because I just wrote a read-election function that takes the full stack of user ocds, and it would be good to know if that's going to be a problem.

**Comment by mrichards42** [comment]
Yeah, basically. The `read-*` functions are use uuids, so that's fine, but the `search-*` functions are using a list of ocd-ids. We only ever `search-election-authorities` with the single local authority that needs to be fetched, so again, that one is probably fine, but `serach-elections` happens with the entire list of ocd-ids for a user, so that could definitely blow up. We're using TTL on that, so the cache is basically unbounded for the 5 minute TTL.

It wouldn't be bad to add some logging in the cache wrapper as well.

**Comment by mrichards42** [comment]
I think we want something like LRU + TTL

**Comment by mrichards42** [comment]
Another way out of this (perhaps) would be to create a separate backing store for election authorities and elections. We're not only storing a bunch of ocd-ids as cache keys, but we're also storing _copies_ of the full election/authority data as the values in the cache.

```clj
(def cache (atom {}))
;; when we get an election
(swap! cache assoc ocd-ids election)
```

We could instead store election-ids and have a separate cache with the actual elections:
```clj
(def cache (atom {}))
(def elections-cache (atom {}))
;; when we get an election
(swap! elections-cache assoc (:id election) election))
(swap! cache assoc ocd-ids (:id election))
```

That's definitely more hairy, but if we end up with a situation where we just need to have a bunch of duplicate data like that, it could save a lot of memory.

**Comment by eggsyntax** [comment]
Seems like it might also make sense to break up the caching by ocd-id? Haven't really looked at the code, but it seems like we could split it up and cache `ocd-id`->`election-id` for each ocd-id?

Guessing we'd have to change the actual db search to make that work, but I'm not sure we'd pay a perf cost for that, and we'd get a lot more cache hits.

**Comment by mrichards42** [comment]
🤷‍♂️ I might have raised the alarm a little too early on this. I think `search-elections` only ends up being called from a user-initiated action (rather than an election-initiated action). This should only be a potential problem during high site use, but not during an election import. Still might want to think about tuning our caches so that they have a bound on the number of items.

**Pull request merged**
