### PR TITLE
[TH DG] Added an NREPL server on port 1507

### PR DESCRIPTION
**Pull request by danielglauser**
This should really help improve our dev workflow. There are more things to do here, however if you follow the instructions this works and will get you a connected REPL in dev.

TODO:
1. Figure out how to have cider-connect work against localdocker instead of having to use the IP.
1. Enable this in production.
1. Profit.

### CODE REVIEW

**Comment by danielglauser** [comment]
@cap10morgan @tie-rack Would love either of you to weigh in on this.

**Comment by ericnormand** [comment]
I like it. Does this mean we also have nrepl running in production?

**Comment by cap10morgan** [comment]
I like the goal of being able to connect to a REPL in whatever environment an app is running in. But would it be better to just use something like `docker exec foo lein repl :headless` and connect to that?

With this approach, we'd be connecting to apps deployed in WildFly (did we ensure they all use a different port number?), and would potentially be able to crash the app, the entire WildFly server, etc. I realize running a REPL in production is already a "with great power comes great responsibility" scenario, but I'd like to hear others' thoughts on which approach would be safer (if there even is a meaningful difference).

**Comment by danielglauser** [comment]
@ericnormand I believe that we'll still have some port mapping shenanigans to do in production but once that is done, yeah, we'll have NREPL in prod too.

**Comment by danielglauser** [comment]
@cap10morgan With the approach you suggested we would spin up a separate JVM. It would offer some protection from crashing the running instance, if you executed something in the REPL and it completely blew up you could just shutdown the new JVM. I believe that the new JVM would be the same size as the existing JVM so we'd have to make sure there was enough room on the box and we don't crash the entire box by spinning up too many JVMs. The approach we picked does have its tradeoffs, I'm glad we are discussing them.

**Comment by cap10morgan** [comment]
@danielglauser Yes it would, but with the WildFly deployments we're sharing one JVM among the deployed apps. So spinning up a lein repl would launch a JVM in the app's container. In theory we'd have 1 JVM per server (assuming all JVM apps run in the wildflies) + N JVMs per REPL, which would hopefully usually be 0 and sometimes be 1 or 2.

**Comment by ericnormand** [comment]
@danielglauser ok. That's scary. I don't think we want that.

**Comment by tank157** [comment]
We can still do damage spinning up a separate JVM. In particular, if we run the queue/initialize, we now start consuming messages, and any changes we make to existing message handling code could leave those messages in a bad state.

**Comment by ericnormand** [comment]
I think we want the running server, not just lein repl. At a point very soon, we will want to have servers running locally for development (not just the repl). I don't think I run `docker compose up` very much, so it doesn't look too useful to me to run that. I'm not averse to changing my workflow, but I guess I like running the servers all locally.

**Comment by ericnormand** [comment]
Perhaps having an nrepl server accessible would change that. Because the problem has always been the lack of feedback.

**Comment by cap10morgan** [comment]
@tank157 Yep, there's no free lunch here w/r/t being careful w/ a REPL in production.

@ericnormand I'm not sure I follow how the REPL architecture question at hand impacts the dev workflow one way or the other. Can you elaborate?

**Comment by tank157** [comment]
@ericnormand yeah, with this workflow you get immediate feedback, and now don't necessarily have to manually spin up a bunch of services should you want to manually test across the rabbit boundary.

**Comment by cap10morgan** [comment]
@ericnormand & @tank157 Are we talking about testing things in production REPLs as a shortcut to spinning up multiple components in dev? Or something else?

**Comment by tank157** [comment]
@cap10morgan No no, if I'm reading you right, we're not proposing we just start testing things out in production because it's hard to bring them up in dev. We're proposing that this Dockerfile change allows us to craft docker-compose.yml files that link ports up, and we use those in dev to spin multiple components up AND retain the ability to connect up repls and hot patch code in a fully operational dev environment.

If I'm reading @ericnormand right, he hasn't used docker-compose locally because running things with `lein run` or whatever gives him the ability to connect up a REPL and shorten the feedback, and until now, the feedback cycle with docker-compose involves stopping the entire cluster, building your code changes, starting it back up again, and then testing from the outside. And that's a very long cycle.

**Comment by danielglauser** [comment]
@tank157 +1 I think you nailed it on the head.

**Comment by tie-rack** [comment]
Oh I like what @tank157 said. And if that's the case, then I'm all aboard.

However, and this is relatively minor: perhaps don't pin the exposed port and let docker handle making unique exposed ports across multiple running instances. It is easy enough to find the port, and we wouldn't have to mind other project's port numbers when adding this to other files.

**Comment by ericnormand** [comment]
You've almost got it @tank157. I usually don't connect a repl to any running server. When I am running the server (which is rarely), it's separate from my repl. Not saying it's a great workflow. It's just a lot of work to make the server code hot reloadable, and I haven't really had to test the server per se (request/response), just the inner code. The repl is for quickly running tests.

**Comment by cap10morgan** [comment]
@tank157 OK, yes, that would be great. And I think we can achieve that with either approach (i.e. the REPL is embedded in the running app or by using `docker exec app lein repl :headless`–which I think could even be its own `repl` entry in `docker-compose.yml`). There are, of course, pros and cons to each approach.

One thing we should be mindful of, though, if we decide to go the embedded route over the `docker exec app lein repl :headless` route, is that we'll need to randomize or otherwise check and increment the port numbers that the embedded REPLs run on even within the containers. Typically each app will be running inside the same wildfly container (at least in production and currently in most docker-compose configs), so they can't all try to listen on the same port. And then we'll need a way to discover or derive those port numbers to know which app's REPL we're connecting to (docker won't help much here, but Consul could).

If we go the `docker exec app lein repl :headless` route, then the above is moot because those will each run in their own containers w/ their own IPs and ports and Docker can do the port mapping for us.

**Comment by tank157** [comment]
@ericnormand Ok, one of the things I've been finding is we have to go back and clean up a lot of the rabbit code that was committed and accepted without actually being exercised because it involved external systems. This has included, but not been limited to: different message keys on sender/receiver, inconsistent queue declarations on either end, incorrect routing keys, missing wire-up-service statement (I'm particularly guilty of that last one). Unit testing has skipped the queue namespace all together, so it's easy to see why. While putting more of the wiring up code into kehaar could help with some of this, and I hope that's the direction you're taking things today, we still need to be able to quickly spin the whole shebang up in dev mode and connect a REPL to test, diagnose, and fix small inconsistencies. Something like this workflow will be a big help in the "spin it all up and figure out what we're missing" card this sprint. And you do seem cool with the idea, just want to re-iterate the value proposition The Ocho and I see in it.

**Comment by tank157** [comment]
@cap10morgan i'd love to see if that approach works. I tried something similar first, but couldn't quite get it working, and when this approach panned out I abandoned the one you are proposing. So if we can get it working, yeah, I think there are definite benefits, like not having special ports or finding randomly assigned ports.

**Comment by danielglauser** [comment]
@tie-rack We thought it would be better to pin each service to its own unique (and repeatable) port, thinking that over time we would memorize the ports. The obvious down side is we will need to manually make sure we don't pick a conflicting port when adding this to a new project. The up side is if you are working on a project for a while you won't have to lookup the port number. If not pinning the services to a port is what gets this through then by all means, I'm ready to concede on that point.

**Comment by cap10morgan** [comment]
@tank157 I've done it before w/ ballot-scout in production and connected to it via CIDER, but I don't have the exact steps memorized. Want to pair on it on Monday?

**Comment by danielglauser** [comment]
Re-pinging the folks here. Now that we've had time to think about this please let me know if you still disagree with this PR. @tank157 and I found it very useful in krakenstein, I think it would help our dev workflow if we had all of our projects expose REPLs on known ports. @cap10morgan @tie-rack @ericnormand

**Comment by cap10morgan** [comment]
I've come around to the embedded REPL idea. There are some issues with the sidecar one that make it less convenient, among other downsides raised in here.

I'm also in favor of pinned ports that are unique to each project so we start to memorize them. But we also need a way to quickly look them up. If that's just putting them in TorchPad, fine. But it seems like we could come up with a command to list them too.

**Comment by danielglauser** [comment]
@cap10morgan The port is announced when the server starts up. Is that enough?

**Comment by cap10morgan** [comment]
@danielglauser It's a start, but probably not sufficient. That would entail digging through logs to find the announced port, which doesn't seem like the best workflow.

**Comment by danielglauser** [comment]
@cap10morgan I've never had to look through a log locally, the output shows up in the console. As far as production goes the REPL port is in the [README](https://github.com/democracyworks/electorate-works/commit/78ceda86f2f5027e2dab5bb3a3400e4b52053881#diff-04c6e90faac2675aa89e2176d2eec7d8R95). Is there something else you are looking for?

**Comment by cap10morgan** [comment]
Yes, I'm thinking of the production (and other deployed use cases, such as docker-compose locally). The READMEs are probably fine for now, though.

**Comment by danielglauser** [comment]
@cap10morgan Cool! Is that a LGTM brand of fine? Would you like the port in big bold letters? @tie-rack @ericnormand Trying to push this to completion so I'd appreciate a yay/nay from you gents as well before I click any buttons.

**Comment by ericnormand** [comment]
Fine by me.

**Comment by tie-rack** [comment]
I concur.

**Comment by cap10morgan** [comment]
Yes, LGTM

**Pull request merged**
