### PR TITLE
Handle user.update events

### PR DESCRIPTION
**Pull request by ericnormand**
user.update events are important because it could indicate that the user
has changed addresses, hence their ocd, hence it invalidates upcoming
electorates. This is addressed by doing a diff of the old set of
electorates with the new set of electorates. There will be
three (potentially empty) sets. New electorates based on the new
address, old electorates based on the old address, and electorates that
are still valid even after a change. New electorates are created, old
electorates are deleted (and generate a delete event), and valid
electorates are let alone but they generate a new electorate.create
event, since this is supposed to be idempotent.

Delete events are new. Election-notification-works is listening for them
to unschedule upcoming election notifications.

An important question this brings up: what is the difference now between
user.create and user.update? It seems that user.create degenerates to
the same case as user.update where old and valid electorates are
empty. For the sake of reducing moving parts, we may want to handle them
with the same code paths.

[Pivotal Card](https://www.pivotaltracker.com/story/show/113401679)

### CODE REVIEW

**Comment by ericnormand** [comment]
A note to the reviewer. The splitting into two commits was done because a large part of this commit was a refactoring. The first commit is the refactoring, the second is the new features. I made attempts to split them correctly, but these might not be 100% refactoring and feature.

**Comment by ericnormand** [comment]
Note: this was working yesterday but I'm doing one final Krakenstein test after removing superfluous print statements and cosmetic changes.

**Comment by ericnormand** [comment]
Update: Krakenstein tests are positive!

**Comment by ericnormand** [comment]
After all these changes, I'm going to test in krakenstein again.

**Comment by ericnormand** [comment]
Can I get a LGTM?

**Comment by cap10morgan** [comment]
I still don't love the single-fn namespaces. Seems like the namespaces should be entity, handler, etc. types and the functions the actions on them.

**Comment by ericnormand** [comment]
Ok, I'll do a refactor.

**Comment by ericnormand** [comment]
Ok, @cap10morgan, refactor done. What do you think?

**Comment by cap10morgan** [comment]
LGTM

**Comment by ericnormand** [comment]
Well, I can change it.

**Comment by ericnormand** [comment]
Done.

**Comment by cap10morgan** [comment]
LEBTM

**Pull request merged**
