### PR TITLE
Make ocd-id-level fn more flexible

### PR DESCRIPTION
**Pull request by cap10morgan**
The fall-through case now returns the key of the last key:value pair in
the OCD-ID. So you'll get :borough from
ocd-division/country:us/state:ak/borough:bfe, for example.

This came out of Troy and I discussing how to handle DC's `district` level and Alaska's `borough` variations.

Any reason we shouldn't do it this way?

### CODE REVIEW

**Comment by ericnormand** [comment]
Will this open us up to unlimited levels? And do we want that?

In the old scheme, we would have added district and borough, presumably making district return :state and borough return :municipal.

**Comment by cap10morgan** [comment]
@ericnormand It does and I think we do because there's no reason (I can think of) why we need to lump parish in with county, district in with state, etc. And borough isn't municipal (it's closer to county), but is its own thing that will likely need some special handling.

Do you see a downside to letting DC use `:district`, LA `:parish`, etc.?

**Comment by ericnormand** [comment]
There is a downside, but I don't know enough to know how big it is and whether it's worth it. So don't consider this conversation a blocker. The downside I see is that people tend to forget about parishes. They say "search all election by level" and then they say county, but forget that they also need to say OR parish. Just one more thing to remember/get wrong/murphy's law.

Like I said, not a blocker. I don't think we have that query. And I think everything in this thing LOOKS GOOD TO ME.

**Comment by ericnormand** [comment]
Just a note: this PR is implicitly saying we're treating all states separately, instead of trying to unify them under a simpler rubric of state/county/municipal. We should note that don't somewhere to guide design decisions in the future.

**Comment by cap10morgan** [comment]
@ericnormand I actually don't think it *is* implicitly saying that. We can (and do) still map local variations to their more common counterparts (like `:parish` -> `:county`) when it makes sense to do so. All it does is allow us to use the actual key in the OCD-ID when we want to (which we were already doing for `:state` and `:county` when those matched the OCD-ID). We may still decide to do more of those mappings when they are fully / effectively equivalent, but this allows us to use the actual level without adding a redundant mapping when they are not.

**Comment by ericnormand** [comment]
LGTM

**Comment by cap10morgan** [comment]
Your point about having to remember parish if you want a grouping of everything at the county level is a very good one. I think we'll leave the parish -> county mapping in place for that reason. And then we need to make sure we only use something different when it's actually meaningfully different.

Thanks for the thoughtful review.

**Pull request merged**
