### PR TITLE
use v2 elections in election.create events

### PR DESCRIPTION
**Pull request by cap10morgan**
I'm about to build a new election HTTP API and I didn't want to code the now-deprecated `v2` queue names into another place.

It *seems* like the only change we need to make to electorate-works (or any other component for that matter) to work exclusively with v2 elections is this one-line change (or similar).

So that seems worth doing and dropping the v1 support, and then dropping the `v2` queue names from election-works altogether.

### CODE REVIEW

**Comment by ericnormand** [comment]
Just a question: What does this PR have to do with the v2 queue names? Or is that just a comment on your plan?

**Comment by cap10morgan** [comment]
Just a comment on my plan.

**Comment by ericnormand** [comment]
Have you tested this in krakenstein?

**Comment by cap10morgan** [comment]
I... can't remember. I'll do it (again?).

**Comment by ericnormand** [comment]
Yes please. It would be nice to know that the messages still work.

**Comment by cap10morgan** [comment]
OK, I ran it in krakenstein and found some other things I needed to fix. The root of those changes is [this election-notification-works PR](https://github.com/democracyworks/election-notification-works/pull/35).

**Comment by ericnormand** [comment]
LGTM

**Pull request merged**
